In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import scipy.stats as stats

In [2]:
df_member = pd.read_csv(r'C:\Users\UserK\Desktop\Ranee\data\ML\유아용품판매데이터\Member_data.csv')
df_product = pd.read_csv(r'C:\Users\UserK\Desktop\Ranee\data\ML\유아용품판매데이터\Product_data.csv')
df_sales =  pd.read_csv(r'C:\Users\UserK\Desktop\Ranee\data\ML\유아용품판매데이터\Sales_data.csv')

C:\Users\UserK\AppData\Local\Temp\ipykernel_20132\2489966323.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_member = pd.read_csv(r'C:\Users\UserK\Desktop\Ranee\data\ML\유아용품판매데이터\Member_data.csv')
C:\Users\UserK\AppData\Local\Temp\ipykernel_20132\2489966323.py:3: DtypeWarning: Columns (1,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sales =  pd.read_csv(r'C:\Users\UserK\Desktop\Ranee\data\ML\유아용품판매데이터\Sales_data.csv')

In [3]:
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199999 entries, 0 to 199998
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  199999 non-null  int64
 1   주문번호        199999 non-null  object
 2   배송완료일       199999 non-null  object
 3   배송시작일       199999 non-null  object
 4   구매일         199999 non-null  object
 5   구매시월령       168142 non-null  float64
 6   고객번호        199999 non-null  object
 7   구매금액        199999 non-null  int64
 8   결제금액        199999 non-null  int64
 9   물품대분류       199999 non-null  object
 10  상품명         199999 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 16.8+ MB

In [4]:
df_sales.sort_values(by='구매시월령',ascending=False)

,Unnamed: 0,주문번호,배송완료일,배송시작일,구매일,구매시월령,고객번호,구매금액,결제금액,물품대분류,상품명
132681,132681,912213225292198097,2022-12-26,2022-12-22,2022-12-21,1439.0,201912211054747,3000,3000,체험팩,맘큐 허그박스
171553,171553,003313603724118211,2023-04-05,2023-04-03,2023-04-02,1215.0,201906040909346,39820,39421,물티슈,[베이비가운증정] 하기스 뉴본케어 물티슈 캡형 64매X20팩
175202,175202,004123655011118212,2023-04-16,2023-04-14,2023-04-13,1215.0,201906040909346,39820,39421,물티슈,[베이비가운증정] 하기스 뉴본케어 물티슈 캡형 64매X20팩
176177,176177,004143662557118213,2023-04-21,2023-04-17,2023-04-16,1215.0,201906040909346,39820,39421,물티슈,[베이비가운증정] 하기스 뉴본케어 물티슈 캡형 64매X20팩
164017,164017,003073502613118205,2023-03-12,2023-03-10,2023-03-09,1214.0,201906040909346,15000,14850,SKC,그린핑거 마이키즈 얼굴로션 160ml
...,...,...,...,...,...,...,...,...,...,...,...
199880,199880,00805150856-8625824494626,2023-08-10,2023-08-08,2023-08-07,NaN,201904160872145,31600,16398,기저귀,NEW 하기스 네이처메이드 이른둥이기저귀 중형 150매(밴드형)
199885,199885,00805153336-62196352193886,2023-08-12,2023-08-08,2023-08-07,NaN,201912171046039,12320,10080,SKC,그린핑거 마이키즈 로션 대용량 330ml (EA)
199914,199914,00806200903-66417349184924,2023-08-12,2023-08-09,2023-08-08,NaN,201911051026236,99900,95902,팬티,NEW 하기스 네이처메이드 팬티 5단계 여아 160매(팬티형)
199915,199915,00806230122-60989359139880,2023-08-11,2023-08-09,2023-08-08,NaN,201907190943018,99800,73588,팬티,하기스 NEW 네이처메이드 썸머팬티 4단계 공용 82매(팬티형)
199963,199963,00806193306-1467870219576,2023-08-11,2023-08-09,2023-08-08,NaN,201901240772904,6900,6693,체험팩,NEW 하기스 네이처메이드 팬티 4단계 여아 20매(팬티형/체험팩) (EA)

In [5]:
df_sales.shape

(199999, 11)

In [7]:
df_sales.loc[df_sales['물품대분류'] == '체험팩']

,Unnamed: 0,주문번호,배송완료일,배송시작일,구매일,구매시월령,고객번호,구매금액,결제금액,물품대분류,상품명
5,5,812311863130184,2022-01-04,2022-01-02,2022-01-01,5.0,201812310749957,27920,19900,체험팩,[하기스 샘플러_3단계 여아] + 매직핏팬티 체험팩
6,6,901011864197295,2022-01-06,2022-01-02,2022-01-01,0.0,201901010750075,27920,19900,체험팩,[하기스 샘플러_3단계 여아] + 매직핏팬티 체험팩
7,7,901011864459368,2022-01-04,2022-01-02,2022-01-01,5.0,201901010750145,27920,19900,체험팩,[하기스 샘플러_3단계 여아] + 매직핏팬티 체험팩
8,8,901011864652401,2022-01-05,2022-01-02,2022-01-01,NaN,201901010750178,27920,19900,체험팩,[하기스 샘플러_3단계 남아] + 매직핏팬티 체험팩
9,9,901011864990488,2022-01-04,2022-01-02,2022-01-01,8.0,201901010750269,27920,19900,체험팩,[하기스 샘플러_3단계 여아] + 매직핏팬티 체험팩
...,...,...,...,...,...,...,...,...,...,...,...
199961,199961,00806150825-91095426148459,2023-08-11,2023-08-09,2023-08-08,17.0,201908070956563,7900,7821,체험팩,NEW 하기스 맥스드라이 팬티 5단계 공용 20매(팬티형/체험팩) (EA)
199962,199962,00806164710-16837426172756,2023-08-11,2023-08-09,2023-08-08,11.0,201910101002931,7900,7505,체험팩,NEW 하기스 맥스드라이 팬티 5단계 공용 20매(팬티형/체험팩) (EA)
199963,199963,00806193306-1467870219576,2023-08-11,2023-08-09,2023-08-08,NaN,201901240772904,6900,6693,체험팩,NEW 하기스 네이처메이드 팬티 4단계 여아 20매(팬티형/체험팩) (EA)
199964,199964,00806152539-84881161156334,2023-08-11,2023-08-09,2023-08-08,6.0,201908260970433,5900,5841,체험팩,NEW 하기스 네이처메이드 3단계 여아 20매(밴드형/체험팩) (EA)
199965,199965,00806162031-341981748356,2023-08-11,2023-08-09,2023-08-08,31.0,201901130758792,3000,3000,체험팩,맘큐 허그박스

In [6]:
df_sales.isnull().sum()

Unnamed: 0        0
주문번호              0
배송완료일             0
배송시작일             0
구매일               0
구매시월령         31857
고객번호              0
구매금액              0
결제금액              0
물품대분류             0
상품명               0
dtype: int64

In [ ]:
df_sales['구매시월령'].describe()

In [ ]:
df_product.isnull().sum()

In [6]:
a = df_product['상품명'].unique().tolist()

In [7]:
df_product.loc[df_product['상품명'] == '[대량발주] 택배파손_1224']

  물품대분류               상품명  물품판매량   제품단가
8    FC  [대량발주] 택배파손_1224      1  35500

In [8]:
df_member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81360 entries, 0 to 81359
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   고객번호    81360 non-null  object
 1   성별      81094 non-null  object
 2   결혼유무    81094 non-null  object
 3   거주지역    81094 non-null  object
 4   연령      81094 non-null  float64
 5   결제등록카드  81094 non-null  object
 6   유입경로    81094 non-null  object
 7   자녀여부    81094 non-null  object
dtypes: float64(1), object(7)
memory usage: 5.0+ MB

In [9]:
df_member.head(10)

              고객번호 성별 결혼유무 거주지역    연령 결제등록카드    유입경로 자녀여부
0  201812310749735  여   기혼   인천  37.0   국민은행   인스타그램  Yes
1  201812310749770  여   기혼   제주  33.0   국민은행    검색광고  Yes
2  201812310749771  여   기혼   부산  32.0   하나은행  네이버블로그  Yes
3  201812310749774  여   미혼   경남  34.0   기업은행    지인추천   No
4  201812310749780  여   기혼   서울  32.0   신한은행    직접검색  Yes
5  201812310749783  여   미혼   경기  26.0   광주은행    검색광고   No
6  201812310749784  여   기혼   충북  33.0   국민은행  네이버블로그  Yes
7  201812310749787  여   기혼   광주  35.0   BC카드  네이버블로그  Yes
8  201812310749792  여   기혼   서울  33.0   우리은행  네이버블로그  Yes
9  201812310749802  여   기혼   충남  36.0   신한은행  네이버블로그  Yes

In [14]:
df_product.loc[df_product['상품명'].str.contains('박스')]

     물품대분류                                               상품명  물품판매량    제품단가
931     기타         [드시모네] ★5포 추가증정★ 드시모네 곰돌이 츄어블 2박스 (80정*2)      1   80000
932     기타             [드시모네] ★추가증정 6캡슐★ 드시모네 베이비드롭 1박스 (1병)      2   38000
933     기타                      [드시모네] 드시모네 곰돌이 츄어블 1박스(80정)     10   37600
934     기타                   [드시모네] 드시모네 곰돌이 츄어블 2박스 (80정*2)      3  106667
935     기타                         [드시모네] 드시모네 데일리 1박스 (30포)      1  108000
936     기타                     [드시모네] 드시모네 베이비 캡슐 1박스 (30캡슐)     12   38000
937     기타          [드시모네] 드시모네 베이비 캡슐 1박스 (30캡슐) + 6캡슐 추가증정      1   38000
938     기타                        [드시모네] 드시모네 베이비드롭 1박스 (1병)     13   43846
939     기타             [드시모네] 드시모네 베이비드롭 1박스 (1병) + 6캡슐 추가증정      1   38000
940     기타                         [드시모네] 드시모네 캡슐 1박스 (60캡슐)      1   98000
941     기타                      [드시모네] 드시모네 키즈프리미엄 1박스 (30포)      3  117333
1019    기타                          [레고] 10696_클래식 미디엄 조립 박스      2   41900
1045    기타        [레고] 10909_듀플로 하트 박스+러기지택 + 하기스 아기물티슈2팩 증정      1   26900
1047    기타                              [레고] 10913_듀플로 브릭 박스      1   40400
1048    기타                          [레고] 10914_듀플로 디럭스 브릭 박스      1   74900
1066    기타             [레고][EVENT] 10864_듀플로 놀이터 브릭박스+3종 사은품      1   53800
1134    기타                  [맘스앱솔루트] 코코아 20g 10팩x2박스 (총 20팩)      1   12900
1298    기타                [보쉬토이] 툴박스 (KL8214) / 보쉬 공구놀이 역할놀이      1   42000
1365    기타                                    [비박스]다용도 실리콘커버      5   13500
1366    기타                                [비박스]스텐 원터치 보냉 빨대컵      5   25960
1367    기타                                  [비박스]외출용 휴대용 턱받이      1   20000
1368    기타                                 [비박스]원터치 트라이탄 빨대컵      2   24900
1369    기타                      [비박스]원터치 트라이탄 빨대컵 리필세트+세척솔증정      1   12900
1370    기타                                    [비박스]유아 스푼포크세트      1   14500
1371    기타                                   [비박스]이유식 방수 턱받이      1   10400
2526   물티슈  [쿠폰적용가15,500원] 닥터마밍 수딩케어 아기물티슈 휴대형 20매x20팩 X 2박스     10   37200
2527   물티슈   [쿠폰적용가15,900원] 닥터마밍 모이스쳐 아기물티슈 캡형 72매x10팩 X 2박스     62   35903
2528   물티슈  [쿠폰적용가15,900원] 닥터마밍 촉촉케어 아기물티슈 리필형 72매x10팩 X 2박스     47   37889
2557   물티슈                   릴리유 퓨어골드 아기물티슈 캡형 80매X10팩 X 2박스    102   37555
2626   체험팩                                           맘큐 허그박스  12077    3000

In [9]:
df1 = pd.merge(df_sales, df_member, on='고객번호')

# 체험팩을 구매한 고객들에 대한 현황 조사

In [11]:
df1['count'] =1

In [14]:
df2 = df1.loc[df1['상품명'].str.contains('체험팩')]

In [37]:
# 체험팩을 구매한 고객들의 체험팩 구매횟수
pv1 = df2.pivot_table(index='고객번호', values='count' , aggfunc='sum').reset_index()

In [38]:
pv1

                       고객번호  count
0           201812310749780      1
1           201812310749784      1
2           201812310749787      1
3           201812310749827      2
4           201812310749839      3
...                     ...    ...
12264  20200614095002296695      1
12265  20200619005724926190      1
12266  20200624152856010330      1
12267  20200630131723621747      1
12268  20200803075905757887      1

[12269 rows x 2 columns]

In [22]:
df1.loc[df1['상품명'].str.contains('체험팩')]['고객번호'].tolist()

[201812310749957,
 201901010750075,
 201901010750145,
 201901010750178,
 201901010750269,
 201812310749946,
 201812310749946,
 201812310750017,
 201812310750044,
 201901010750264,
 201812310749890,
 201812310749839,
 201812310749839,
 201812310749839,
 201812310750008,
 201812310749787,
 201812310750043,
 201901010750282,
 201901010750439,
 201901010750512,
 201901010750512,
 201901010750462,
 201901010750520,
 201901010750520,
 201901010750542,
 201901010750542,
 201901020750736,
 201901020750747,
 201901020750792,
 201901010750399,
 201901020750730,
 201901010750354,
 201901010750275,
 201901010750275,
 201901010750275,
 201901010750385,
 201901010750094,
 201901010750051,
 201901010750051,
 201901020751256,
 201901030751631,
 201901010750306,
 201901020751295,
 201901020750917,
 201901020751114,
 201901020751240,
 201901030751586,
 201901020751224,
 201901020751192,
 201901020751341,
 201901020751341,
 201901020751085,
 201901020751085,
 201901020751144,
 201901020751144,
 201901020751144,
 201901020751144,
 201901020751144,
 201901020751144,
 201901020750977,
 201901030751425,
 201901030751990,
 201901030752085,
 201901040752128,
 201901040752262,
 201901030751660,
 201901030751889,
 201901030751959,
 201901030752067,
 201901040752432,
 201901030751740,
 201901030752072,
 201901030752072,
 201901030752072,
 201901030752072,
 201901030752072,
 201901040752459,
 201901040752459,
 201901040752459,
 201901020751351,
 201901010750144,
 201901030752099,
 201901040752548,
 201901040752710,
 201901040752774,
 201901040752774,
 201901040752774,
 201901040752577,
 201901010750375,
 201901040752236,
 201901040752236,
 201901020750971,
 201901040752300,
 201901040752736,
 201901040752736,
 201901040752736,
 201901050753358,
 201901050753463,
 201901050753463,
 201901050753463,
 201901050753463,
 201901050753463,
 201901050753463,
 201901060753555,
 201901050753298,
 201901050753361,
 201901060753704,
 201901050753174,
 201901050753235,
 201901050753238,
 201901050753253,
 201901060753691,
 201901010750133,
 201901020750939,
 201901040752685,
 201901050753129,
 201901060754088,
 201901070754417,
 201901070754245,
 201901070754245,
 201901060753816,
 201901060753816,
 201901040752582,
 201901060753604,
 201901060753661,
 201901050753276,
 201901060753836,
 201901070754434,
 201901070754629,
 201901070754474,
 201901070754584,
 201901080755174,
 201901080755174,
 201901080755174,
 201901030751452,
 201901030751452,
 201901030751452,
 201901030751452,
 201901070754906,
 201901070754991,
 201901080755367,
 201901080755009,
 201901080755170,
 201901080755088,
 201901080755088,
 201901080755088,
 201901070754981,
 201901080755693,
 201901090755971,
 201901090756003,
 201901090756166,
 201901090756214,
 201901030751474,
 201901080755530,
 201901080755775,
 201901090756180,
 201901090756180,
 201901080755771,
 201901080755771,
 201901080755735,
 201901090755926,
 201901050753379,
 201901080755516,
 201901080755370,
 201901080755523,
 201901080755523,
 201901090756128,
 201901080755627,
 201901080755627,
 201901090756231,
 201901090756433,
 201901090756433,
 201901090756433,
 201901090756699,
 201901100756795,
 201901100756907,
 201901100756927,
 201901100756988,
 201901100756988,
 201901100757073,
 201901080755812,
 201901080755812,
 201901080755812,
 201901080755812,
 201901080755812,
 201901080755812,
 201901080755812,
 201901080755812,
 201901090756510,
 201901090756438,
 201901090756501,
 201901090756593,
 201901090755949,
 201901090756547,
 201901070754503,
 201901070754503,
 201901090756685,
 201901090756457,
 201901100757220,
 201901100757409,
 201901100757409,
 201901110757760,
 201901100757404,
 201901080755035,
 201901100757231,
 201901100757231,
 201901100757231,
 201901110757638,
 201901040752458,
 201901090756436,
 201901090756436,
 201901100756984,
 201901100757354,
 201901100757354,
 201901100757354,
 201901100757354,
 201901100757354,
 201901110757644,
 201901110757644,
 201901110757644,
 201901110757644,
 201901110757644,
 201901110757644,
 201901100757102,
 201901110757700,
 201901110757700,
 201901110757700,
 201901100757056,
 201812310750012,
 201901100757292,
 201901060754161,
 201901060754161,
 201901060754161,
 201901060754161,
 201901060754161,
 201901100756815,
 201901100756815,
 201901100756815,
 201901110757488,
 201901110757488,
 201901090755913,
 201901090755913,
 201901100757233,
 201901110758024,
 201901120758236,
 201901110757814,
 201901110757814,
 201901110757814,
 201901110757734,
 201901110757734,
 201901110758015,
 201901110758015,
 201901120758154,
 201901120758154,
 201901120758154,
 201901120758154,
 201901120758154,
 201901120758154,
 201901120758154,
 201901120758237,
 201901110757958,
 201901110757978,
 201901100756967,
 201901100756967,
 201901100756967,
 201901100756967,
 201901100756967,
 201901100756967,
 201901100756967,
 201901100756967,
 201901100756967,
 201901100756967,
 201901100756967,
 201901100756967,
 201901100756967,
 201901130758681,
 201901130758777,
 201901120758336,
 201901120758336,
 201901120758336,
 201901120758475,
 201901060754085,
 201901060754085,
 201901110757919,
 201901120758539,
 201901120758539,
 201901120758539,
 201901120758539,
 201901120758539,
 201901130758829,
 201901130758848,
 201901140759187,
 201901140759187,
 201901140759453,
 201901140759453,
 201901130758885,
 201901140759301,
 201901140759443,
 201901140759148,
 201901140759177,
 201901120758557,
 201901130758876,
 201901130758876,
 201901130758889,
 201901130758889,
 201901130758889,
 201901090756450,
 201901130759088,
 201901140759478,
 201901140759478,
 201901140759478,
 201901140759252,
 201901110757838,
 201901110757838,
 201901140759277,
 201901140759277,
 201901030751382,
 201901030751382,
 201901140759556,
 201901080755489,
 201901120758561,
 201901130759049,
 201901130759049,
 201901130759049,
 201901130759049,
 201901140759737,
 201901150760006,
 201901150760006,
 201901150760139,
 201901150760214,
 201901150760777,
 201901150760061,
 201901150760135,
 201901150760135,
 201901150760399,
 201901090756343,
 201901140759744,
 201901140759744,
 201901140759821,
 201812310749902,
 201901060754026,
 201901140759516,
 201901150760041,
 201901140759710,
 201901140759710,
 201901140759710,
 201812310749852,
 201901050752974,
 201901010750401,
 201901080755387,
 201901080755387,
 201901120758055,
 201901150760050,
 201901150760050,
 201901150759997,
 201901160762074,
 201901130758753,
 201901150761611,
 201901150761611,
 201901150761629,
 201901150761061,
 201901150761061,
 201901150761061,
 201901150761659,
 201901150759945,
 201901150759945,
 201901150759945,
 201901150759945,
 201901150760136,
 201901160762186,
 201901160762186,
 201901160762316,
 201901160762316,
 201901160762316,
 201901160762316,
 201901160762316,
 201901160762506,
 201901010750418,
 201901010750418,
 201901010750418,
 201901010750418,
 201901010750418,
 201901010750418,
 201901150761521,
 201901130758868,
 201901010750570,
 201901010750570,
 201901160762320,
 201901100757379,
 201901160762220,
 201901040752413,
 201901130758856,
 201901130758856,
 201901130758856,
 201901140759462,
 201901150761560,
 201901160762260,
 201901170764370,
 201901170764424,
 201901170764429,
 201901170764599,
 201901170764659,
 201901170764911,
 201901170764911,
 201901170764911,
 201901160762974,
 201901160763209,
 201901160763356,
 201901160763525,
 201901160763525,
 201901160763525,
 201901170763835,
 201901170764079,
 201901170764079,
 201901170764079,
 201901170764326,
 201901170764552,
 201901170764552,
 201901170764552,
 201901150761314,
 201901170763668,
 201901170763799,
 201901170764378,
 201901170764469,
 201901170763641,
 201901170764022,
 201901140759546,
 201901140759546,
 201901160763626,
 201901170763783,
 201901170764645,
 201901090756146,
 201901160763434,
 201901160763538,
 201901110757820,
 201901110757929,
 201901110757929,
 201901060753621,
 201901100757295,
 201901160762912,
 201901170764652,
 201901040752161,
 201901040752268,
 201901040752268,
 201901160762630,
 201901180766392,
 201901180766532,
 201901170765970,
 201901180766342,
 201901180766536,
 201901180766646,
 201901170765105,
 201901170765507,
 201901170765507,
 201901170766103,
 201901170766103,
 201901170766150,
 201901170766150,
 201901170766087,
 201901170766134,
 201901170765450,
 201901090755967,
 201901180766434,
 201901160762586,
 201901160762586,
 201901160762586,
 201901140759685,
 201901100757203,
 201901170766097,
 201901160762315,
 201901010750508,
 201901040752607,
 201901070754891,
 201901070754891,
 201901070754891,
 201901070754891,
 201901070754891,
 201901070754891,
 201901070754891,
 201901170765037,
 201901170765037,
 201901170765037,
 201901170765037,
 201901180766777,
 201901180766979,
 201901190767311,
 201901190767318,
 201901190767323,
 201901190767391,
 201901190767396,
 201901190767511,
 201901190767620,
 201901180767031,
 201901190767690,
 201901170764095,
 201901170764103,
 201901180767243,
 201901190767666,
 201901190767666,
 201901190767666,
 201901170765902,
 201901170765902,
 201901180766455,
 201901110757689,
 201901110757689,
 201901050753175,
 201901180767303,
 201901190767421,
 201901190767421,
 201901070754959,
 201901160763427,
 201901170764648,
 201901170764648,
 201901190768106,
 201901190768106,
 201901200768518,
 201901200768518,
 201901040752839,
 201901200768230,
 201901190768060,
 201901190768075,
 201901200768194,
 201901200768198,
 201901200768198,
 201901200768254,
 201901200768254,
 201901200768419,
 201901200768419,
 201901200768419,
 201901200768419,
 201901200768419,
 201901200768214,
 201901200768463,
 201901160763007,
 201901180767153,
 201901090756028,
 201901140759394,
 201901210769546,
 201901200768226,
 201901200768226,
 201901200768226,
 201901210769110,
 201901200768573,
 201901200768577,
 201901200768600,
 201901200768821,
 201901200768821,
 201901200768821,
 201901190767522,
 201901200768513,
 201901200768513,
 201901210769620,
 201901140759741,
 201901190767670,
 201901190767670,
 201901200768720,
 201901200768750,
 201901200769059,
 201901210769512,
 201901170765331,
 201901170765331,
 201901170765331,
 201901170765331,
 201901160762971,
 201901190768151,
 201901190768151,
 201901210769358,
 201901200768578,
 201901190768157,
 201901200768594,
 201901170765896,
 201901170765937,
 201901190767403,
 201901210770275,
 201901220770460,
 201901160762731,
 201901180767193,
 201901210769324,
 201901210770241,
 201901120758115,
 201901120758115,
 201901210770283,
 201901220770385,
 201901200768996,
 201901200768996,
 201901200768996,
 201901210769921,
 201901210770158,
 201901220770401,
 201901210770012,
 201901220770458,
 201901150760913,
 201901150760913,
 201901150760913,
 201901150760913,
 201901150760913,
 201901210770228,
 201901210769149,
 201901210769149,
 201901210770174,
 201901210770174,
 201901180767206,
 201901220770860,
 201901160762574,
 201901160762574,
 201901160762574,
 201901210769914,
 201901210770144,
 201901210770308,
 201901210770043,
 201901210770043,
 201901200768407,
 201901150761149,
 201901220770495,
 201901230771783,
 201901230771848,
 201901140759911,
 201901140759911,
 201901140759911,
 201901140759911,
 201901140759911,
 201901210770231,
 201901220771453,
 201901030751961,
 201901180766220,
 201901190767733,
 201901220771335,
 201901230771845,
 201901230771845,
 201901230771845,
 201901230771845,
 201901230771845,
 201901230771845,
 201901230771845,
 201901230771845,
 201901230771845,
 201901230771845,
 201901230771845,
 201901230771845,
 201901230771845,
 201901230771845,
 201901160763234,
 201901160763234,
 201901220771471,
 201901220771370,
 201901220771485,
 201901200768266,
 201901190767791,
 201901110758017,
 201901230771612,
 201901230771612,
 201901100756975,
 201901230772583,
 201901230772232,
 201901050752912,
 201901240773058,
 201901230772206,
 201901230772206,
 201901230772440,
 201901230772466,
 201901230772483,
 201901230772564,
 201901230772152,
 201901230772454,
 201901230772549,
 201901230772549,
 201901230772613,
 201901230772613,
 201901240772840,
 201901200769039,
 201901030751440,
 201901080755431,
 201901100757195,
 201901230772195,
 201901230772195,
 201901230772195,
 201901230772195,
 201901230772195,
 201901220771411,
 201901040752847,
 201901040752847,
 201901040752847,
 201901240773723,
 201901240773773,
 201901140759548,
 201901170763617,
 201901210769486,
 201901210769486,
 201901230771888,
 201901230772087,
 201901230772087,
 201901240773591,
 201901240773643,
 201901250774089,
 201901250774089,
 201901250774089,
 201901250774269,
 201901100756891,
 201901100756891,
 201901100756891,
 201901100756891,
 201901120758260,
 201901180767214,
 201901240772767,
 201901240772767,
 201901240772767,
 201901240773624,
 201901250773887,
 201901250774075,
 201901250774075,
 201901250774075,
 201901250774075,
 201901150761057,
 201901240773371,
 201901250773990,
 201901250774416,
 201901210769144,
 201901220771275,
 201901250774378,
 201901010750267,
 201901250774109,
 201901150760744,
 201901170764104,
 201901160762916,
 201901220771401,
 201901220771401,
 201901220771401,
 201901220771401,
 201901130758822,
 201901130758822,
 201901130758822,
 201901130758822,
 201901180767222,
 201901240772795,
 201901240772795,
 201901240772795,
 201901250774560,
 201901250774629,
 201901250774629,
 201901250774755,
 201901250774853,
 201901250774853,
 201901250774853,
 201901250774853,
 201901250774853,
 201901260775316,
 201901260775379,
 201901260775394,
 201901260775394,
 201901010750498,
 201901010750498,
 201901010750498,
 201901010750498,
 201901010750498,
 201901010750498,
 201901150760329,
 201901150760692,
 201901150760692,
 201901150760692,
 201901190768160,
 201901250774303,
 201901250774525,
 201901250774804,
 201901250774804,
 201901250774804,
 201901250774804,
 201901250774963,
 201901150760642,
 201901250774512,
 201901250774512,
 201901260775041,
 201901260775261,
 201901190767685,
 201901190767685,
 201901240773593,
 201901160762620,
 201901250774439,
 201901250774439,
 201901250774439,
 201901080755298,
 201901080755298,
 201901080755298,
 201901260775311,
 201901140759580,
 201901140759580,
 201901140759580,
 201901260775720,
 201901260775720,
 201901260775720,
 201901260775720,
 201901260775637,
 201901260775639,
 201901260775712,
 201901270776039,
 201901260775414,
 201901260775414,
 201901260775414,
 201901270776163,
 201901270776163,
 201901020751241,
 201901120758056,
 201901160763528,
 201901160763528,
 201901230772527,
 201901250774447,
 201901250774447,
 201901250774447,
 201901250774447,
 201901270776254,
 201901270776254,
 201901270776254,
 201901270776254,
 201901150760115,
 201901150760115,
 201901150760115,
 201901150761164,
 201901150761164,
 201901260775427,
 201901270776121,
 201901270776383,
 201901270776383,
 201901270776505,
 201901270776513,
 201901270776526,
 201901270776537,
 201901270776537,
 201901280776731,
 201901280776860,
 201901280776860,
 201901280777386,
 201901280777386,
 201901160763317,
 201901270776459,
 201901270776459,
 201901270776459,
 201901270776459,
 201901270776459,
 201901270776459,
 201901270776459,
 201901280776946,
 201901280777052,
 201901280777052,
 201901280777052,
 201901280777239,
 201901160762746,
 201901160762746,
 201901160762746,
 201812310749932,
 201901270776408,
 201901240773229,
 201901250774851,
 201901270776546,
 201901270776528,
 201901270776528,
 201901150760105,
 201901180767227,
 201901280776935,
 201901270776219,
 201901270776219,
 201901230771696,
 201901260775049,
 201901180767263,
 201901270776210,
 201901270776210,
 201901190767846,
 201901200768777,
 201901280777982,
 201901150761439,
 201901250774817,
 201901250774817,
 201901270776144,
 201901270776144,
 201901280777693,
 201901280777933,
 201901280777933,
 201901280777933,
 201901280777933,
 201901280777933,
 201901280777933,
 201901280777980,
 201901280777980,
 201901290778422,
 201901290778422,
 201901290778422,
 201901290778422,
 201901290778709,
 201901210769644,
 201901250774812,
 201901250774812,
 201901290778473,
 201901150760334,
 201901150760334,
 201901280777211,
 201901280777211,
 201901280777657,
 201901280777943,
 201901160762822,
 201901160762822,
 201901280778162,
 201901060753928,
 201901230772370,
 201901130758966,
 201901290779635,
 201901290779635,
 201812310749780,
 201901270776422,
 201901270776422,
 201901290779322,
 201901290779362,
 201901290779383,
 201901290779633,
 201901290779633,
 201901290779633,
 201901290779633,
 201901300779871,
 201901300779915,
 201901300779915,
 201901300779915,
 201901300779915,
 201901300779915,
 201901300779915,
 201901300779915,
 201901300779915,
 201901150760740,
 201901290779338,
 201901020751225,
 201901020751225,
 201901220771520,
 201901260775211,
 201901300780009,
 201901300780009,
 201901300779960,
 201901220770951,
 201901220770951,
 201901210770082,
 201901160763308,
 201901100756799,
 201901270776149,
 201901270776149,
 201901300779852,
 201901060753731,
 201901060753731,
 201901300780255,
 201901300780255,
 201901300780255,
 201901300780487,
 201901300780487,
 201901300780487,
 201901300780319,
 201901110757682,
 201901110757682,
 201901110757682,
 201901290779490,
 201901270776655,
 201901100756761,
 201901100756761,
 201901100757274,
 201901100757274,
 201901300782470,
 201901300782470,
 201901300780963,
 201901300781169,
 201901300781169,
 201901300781169,
 201901300782916,
 201901300782916,
 201901310783904,
 201901310784044,
 201901310784324,
 201901310784324,
 201901310784413,
 201901160763429,
 201901210769751,
 201901300780669,
 201901300780669,
 201901300782325,
 201901300782325,
 201901300782625,
 201901310782997,
 201901170765422,
 201901170765422,
 201901300781089,
 201901300781089,
 201901300781089,
 201901300781331,
 201901300782324,
 201901300782488,
 201901300782557,
 201901310783610,
 201901310783744,
 201901310784169,
 201901310784169,
 201901310784169,
 201901310784169,
 201901310784222,
 201901310784222,
 201901020750595,
 201901300782036,
 201901300782472,
 201901300782472,
 ...]

In [26]:
member_number_yam = df1.loc[df1['상품명'].str.contains('체험팩')]['고객번호'].tolist()
cond1 = df1['고객번호'].isin(member_number_yam)
df3 = df1.loc[cond1]

In [27]:
df3

,Unnamed: 0,주문번호,배송완료일,배송시작일,구매일,구매시월령,고객번호,구매금액,결제금액,물품대분류,상품명,성별,결혼유무,거주지역,연령,결제등록카드,유입경로,자녀여부,count
10,5,812311863130184,2022-01-04,2022-01-02,2022-01-01,5.0,201812310749957,27920,19900,체험팩,[하기스 샘플러_3단계 여아] + 매직핏팬티 체험팩,여,기혼,제주,34.0,신한은행,검색광고,Yes,1
11,6,901011864197295,2022-01-06,2022-01-02,2022-01-01,0.0,201901010750075,27920,19900,체험팩,[하기스 샘플러_3단계 여아] + 매직핏팬티 체험팩,여,기혼,인천,29.0,외환은행,인스타그램,Yes,1
12,384,901071880148296,2022-01-12,2022-01-08,2022-01-07,0.0,201901010750075,12900,8672,더블하트,더블하트 SofTouch 모유실감 젖꼭지 S (2입),여,기혼,인천,29.0,외환은행,인스타그램,Yes,1
13,393,901071880148297,2022-01-12,2022-01-08,2022-01-07,0.0,201901010750075,9900,7434,더블하트,더블하트 젖병세정제 거품형 700ml 용기,여,기혼,인천,29.0,외환은행,인스타그램,Yes,1
14,7,901011864459368,2022-01-04,2022-01-02,2022-01-01,5.0,201901010750145,27920,19900,체험팩,[하기스 샘플러_3단계 여아] + 매직핏팬티 체험팩,남,기혼,대구,36.0,국민은행,네이버블로그,Yes,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135481,199786,00805230512-00697530187328,2023-08-11,2023-08-08,2023-08-07,12.0,201911161032029,44300,29346,팬티,NEW 하기스 맥스드라이 팬티 3단계 여아 116매(팬티형) + 보너스 12매 추가증정,여,기혼,경남,29.0,부산은행,지인추천,Yes,1
135482,199811,00805230512-00697530187329,2023-08-11,2023-08-08,2023-08-07,12.0,201911161032029,6350,6286,체험팩,하기스 네이처메이드 오가닉 3단계 여아 20매(밴드형/체험팩) (EA),여,기혼,경남,29.0,부산은행,지인추천,Yes,1
135483,199817,00805230512-00697530187327,2023-08-11,2023-08-08,2023-08-07,12.0,201911161032029,5900,5841,체험팩,NEW 하기스 네이처메이드 팬티 3단계 여아 20매(팬티형/체험팩) (EA),여,기혼,경남,29.0,부산은행,지인추천,Yes,1
135485,199815,00806110255-23536335182130,2023-08-10,2023-08-08,2023-08-07,5.0,201910261020598,5900,5900,체험팩,2020 하기스 매직팬티 컴포트 4단계 남아 20매(팬티형/체험팩) (EA),여,미혼,인천,34.0,기업은행,네이버블로그,No,1
135486,199816,00806110255-23536335182131,2023-08-10,2023-08-08,2023-08-07,5.0,201910261020598,5900,5900,체험팩,NEW 하기스 맥스드라이 3단계 공용 20매(밴드형/체험팩) (EA),여,미혼,인천,34.0,기업은행,네이버블로그,No,1

In [39]:
# 체험팩을 구매한 고객들의 전체 구매횟수
pv2 = df3.pivot_table(index='고객번호', values='count' , aggfunc='sum').reset_index().rename(columns={'count' : 'count_전체'})

In [40]:
pv2

                       고객번호  count_전체
0           201812310749780         1
1           201812310749784         3
2           201812310749787        14
3           201812310749827         3
4           201812310749839         6
...                     ...       ...
12264  20200614095002296695         1
12265  20200619005724926190         1
12266  20200624152856010330         1
12267  20200630131723621747         1
12268  20200803075905757887         1

[12269 rows x 2 columns]

In [42]:
df4 = pd.merge(pv1,pv2,on='고객번호')

In [43]:
df4['차이'] = df4['count_전체'] - df4['count']
df4

                       고객번호  count  count_전체  차이
0           201812310749780      1         1   0
1           201812310749784      1         3   2
2           201812310749787      1        14  13
3           201812310749827      2         3   1
4           201812310749839      3         6   3
...                     ...    ...       ...  ..
12264  20200614095002296695      1         1   0
12265  20200619005724926190      1         1   0
12266  20200624152856010330      1         1   0
12267  20200630131723621747      1         1   0
12268  20200803075905757887      1         1   0

[12269 rows x 4 columns]

In [46]:
df4.loc[df4['count_전체'] > df4['count']*2]

                  고객번호  count  count_전체  차이
1      201812310749784      1         3   2
2      201812310749787      1        14  13
5      201812310749852      1         3   2
7      201812310749876      1         3   2
10     201812310749902      1         3   2
...                ...    ...       ...  ..
12230  201912291058046      1         3   2
12234  201912291058168      1         4   3
12237  201912291058225      1        12  11
12248  201912301058584      1         4   3
12254  201912311058857      1         3   2

[3199 rows x 4 columns]